#pragma once

#include <grpcpp/grpcpp.h>
#include <string>
#include <memory>
#include "raft.grpc.pb.h" // Generated by Protobuf

class PeerClient {
public:
    // Constructor: Creates the channel and stub but doesn't connect yet
    explicit PeerClient(std::string target_address);

    // --- RPC Wrappers ---
    // These return true if the network call was successful (regardless of the vote result)
    // They return false if the peer is unreachable or timed out.

    bool sendRequestVote(const raft::RequestVoteArgs& args, raft::RequestVoteReply* reply);

    bool sendAppendEntries(const raft::AppendEntriesArgs& args, raft::AppendEntriesReply* reply);

    bool sendInstallSnapshot(const raft::InstallSnapshotArgs& args, raft::InstallSnapshotReply* reply);

private:
    std::unique_ptr<raft::RaftService::Stub> stub_;
};